version: '3.8'

x-common-variables: &common-env
  POSTGRES_DB: arpeely_db
  POSTGRES_USER: arpeely_user
  POSTGRES_PASSWORD: arpeely_pass
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  TOPIC_MODEL_NAME: valhalla/distilbart-mnli-12-1

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      <<: *common-env
    ports:
      - "5432:5432"

  fastapi:
    build: .
    depends_on:
      - postgres
    environment:
      <<: *common-env
    ports:
      - "8000:8000"
    command: ["uvicorn", "arpeely_scraper.app.api.main:app", "--host", "0.0.0.0", "--port", "8000"]

  cli:
    build: .
    depends_on:
      - postgres
    environment:
      <<: *common-env
    entrypoint: ["/usr/local/bin/cli_entrypoint.sh"]
    volumes:
      - .:/app
    working_dir: /app
