version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: arpeely_db
      POSTGRES_USER: arpeely_user
      POSTGRES_PASSWORD: arpeely_pass
    ports:
      - "5432:5432"

  fastapi:
    build: .
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: arpeely_db
      POSTGRES_USER: arpeely_user
      POSTGRES_PASSWORD: arpeely_pass
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    command: ["poetry", "run", "uvicorn", "arpeely_scraper.app.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  pgdata:
